source 'https://github.com/CocoaPods/Specs.git'

target 'HLDigitInputField', :exclusive => true do
  pod "HLDigitInputField", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HLDigitInputField", :path => "../"

  pod 'FBSnapshotTestCase'
end
